Fix interfering headers with Qt 6.12 on MSVC
Qt heders after gstreamer header cause:

C:\Craft\windows-msvc2022_64-cl\include\QtCore/qarraydata.h(92): error C2485: '__declspec(__restrict)' is not a recognized extended attribute